export const generatedAudioMockData = [
  {
    id: "69a8d0c9-e5f9-424c-8a5f-08e1321f1497",
    user_id: "36384889-489c-44c6-9b25-289a95a1be9d",
    created_at: "2026-02-21T20:19:09.290Z",
    is_instrumental: false,
    image_custom:
      "https://lalals.s3.amazonaws.com/GenImages/c4a4df43-9a6f-41d2-8912-16e5f3a675c0.jpg",
    image_custom_thumbnail:
      "https://lalals.s3.amazonaws.com/GenImages/c4a4df43-9a6f-41d2-8912-16e5f3a675c0_thumbnail.jpg",
    input_prompt: "Nepali pop sattire rap song",
    audio_length_ms: 0,
    title: "Music AI",
    lyrics_output: null,
    lyrics_output_timestamped: null,
    conversion_status: "GENERATING",
    publishing_status: "PUBLIC",
    conversion_type: "MUSIC_AI",
    play_count: 0,
    like_count: 0,
    file_output_0: null,
    file_output_0_hq: "",
    file_output_high_quality: "",
    file_output_hls: "",
    file_output_vocals: null,
    file_output_vocals_hq: null,
    file_output_instrumental: null,
    file_output_instrumental_hq: null,
    file_output_other: null,
    file_output_other_hq: null,
    file_output_piano: null,
    file_output_piano_hq: null,
    file_output_guitar: null,
    file_output_guitar_hq: null,
    file_output_bass: null,
    file_output_bass_hq: null,
    file_output_drums: null,
    file_output_drums_hq: null,
    is_extracting_vocals: false,
    user: {
      id: "36384889-489c-44c6-9b25-289a95a1be9d",
      created_at: "2026-02-19T19:08:49.497Z",
      username: "yitek82056",
      display_name: "Test",
      image: null,
      image_thumbnail: null,
      total_followers: 0,
      client_plan_identifier: "FREE",
      client_plan_group: "FREE",
      bio: null,
      is_followed_by_requester: false,
      total_likes_received: 0,
      total_generations: 5,
    },
    bpm: null,
    generation_eta: 91,
    dominant_key: null,
    prompt_identifier: "78d8c49b-e085-4baf-bcaf-e32cdbfe7ae1",
    text_result: null,
    version_string: "Version 1",
    comment_count_total: 0,
    pending_comment_count: 0,
    is_liked_by_user: false,
    is_new: true,
    queue_number: 0,
    is_vocals_ready: false,
    is_instrumental_ready: false,
    is_generated_via_tool: false,
    available_downloads: [],
    featured_request_status: null,
    owner_feedback_tag: null,
    owner_feedback_message: null,
  },
  {
    id: "ea418f75-f2e7-4eb0-960b-552e4fec54e6",
    user_id: "36384889-489c-44c6-9b25-289a95a1be9d",
    created_at: "2026-02-21T20:19:09.290Z",
    is_instrumental: false,
    image_custom:
      "https://lalals.s3.amazonaws.com/GenImages/c4a4df43-9a6f-41d2-8912-16e5f3a675c0.jpg",
    image_custom_thumbnail:
      "https://lalals.s3.amazonaws.com/GenImages/c4a4df43-9a6f-41d2-8912-16e5f3a675c0_thumbnail.jpg",
    input_prompt: "Nepali pop sattire rap song",
    audio_length_ms: 153350,
    title: "Masti Beat",
    lyrics_output:
      "[Verse]\nYo, rolling through the hills with a Nepali flow,\nSarangi strings hum where the wild winds blow.\nGolden temples shine while the city lights glow,\nWe hustle hard but we keep it slow.\n\n[Chorus]\nHimalayan groove, feel it in your feet,\nElectronic beats mixed with mountain heat.\nDance like the rivers, wild and sweet,\nThis Nepali rhythm can’t be beat!\n\n[Verse]\nTaxi horns blast in a Kathmandu jam,\nMonkeys steal the show like a scam.\nWe laugh it off with a plate of momo,\nSpicy dreams in this neon promo.\n\n[Chorus]\nHimalayan groove, feel it in your feet,\nElectronic beats mixed with mountain heat.\nDance like the rivers, wild and sweet,\nThis Nepali rhythm can’t be beat!\n\n[Bridge]\nFrom Pokhara lakes to the Everest high,\nWe spin the world with a wink and a sigh.\nDrums punch hard, but the melody flies,\nA satirical twist under open skies.\n\n[Chorus]\nHimalayan groove, feel it in your feet,\nElectronic beats mixed with mountain heat.\nDance like the rivers, wild and sweet,\nThis Nepali rhythm can’t be beat!\n\n[Chorus]\nHimalayan groove, feel it in your feet,\nElectronic beats mixed with mountain heat.\nDance like the rivers, wild and sweet,\nThis Nepali rhythm can’t be beat!",
    lyrics_output_timestamped:
      '[{"start": 8680, "end": 20680, "text": "[Verse]", "index": 0}, {"start": 8680, "end": 12440, "text": "Yo, rolling through the hills with a Nepali flow,", "index": 1}, {"start": 12600, "end": 14920, "text": "Sarangi strings hum where the wild winds blow.", "index": 2}, {"start": 14960, "end": 17080, "text": "Golden temples shine while the city lights glow,", "index": 3}, {"start": 17240, "end": 20680, "text": "We hustle hard but we keep it slow.", "index": 4}, {"start": 21280, "end": 40840, "text": "[Chorus]", "index": 5}, {"start": 21280, "end": 25800, "text": "Himalayan groove, feel it in your feet,", "index": 6}, {"start": 26120, "end": 29160, "text": "Electronic beats mixed with mountain heat.", "index": 7}, {"start": 30280, "end": 34000, "text": "Dance like the rivers, wild and sweet,", "index": 8}, {"start": 35080, "end": 40840, "text": "This Nepali rhythm can’t be beat!", "index": 9}, {"start": 41600, "end": 50680, "text": "[Verse]", "index": 10}, {"start": 41600, "end": 43320, "text": "Taxi horns blast in a Kathmandu jam,", "index": 11}, {"start": 43800, "end": 45720, "text": "Monkeys steal the show like a scam.", "index": 12}, {"start": 46360, "end": 48000, "text": "We laugh it off with a plate of momo,", "index": 13}, {"start": 48600, "end": 50680, "text": "Spicy dreams in this neon promo.", "index": 14}, {"start": 52480, "end": 72280, "text": "[Chorus]", "index": 15}, {"start": 52480, "end": 55560, "text": "Himalayan groove, feel it in your feet,", "index": 16}, {"start": 57000, "end": 61440, "text": "Electronic beats mixed with mountain heat.", "index": 17}, {"start": 61480, "end": 65239, "text": "Dance like the rivers, wild and sweet,", "index": 18}, {"start": 66280, "end": 72280, "text": "This Nepali rhythm can’t be beat!", "index": 19}, {"start": 72960, "end": 83160, "text": "[Bridge]", "index": 20}, {"start": 72960, "end": 74720, "text": "From Pokhara lakes to the Everest high,", "index": 21}, {"start": 74840, "end": 77360, "text": "We spin the world with a wink and a sigh.", "index": 22}, {"start": 77400, "end": 79640, "text": "Drums punch hard, but the melody flies,", "index": 23}, {"start": 79800, "end": 83160, "text": "A satirical twist under open skies.", "index": 24}, {"start": 84080, "end": 111880, "text": "[Chorus]", "index": 25}, {"start": 84080, "end": 87880, "text": "Himalayan groove, feel it in your feet,", "index": 26}, {"start": 88200, "end": 91600, "text": "Electronic beats mixed with mountain heat.", "index": 27}, {"start": 92680, "end": 97440, "text": "Dance like the rivers, wild and sweet,", "index": 28}, {"start": 97480, "end": 111880, "text": "This Nepali rhythm can’t be beat!", "index": 29}, {"start": 121640, "end": 139560, "text": "[Chorus]", "index": 30}, {"start": 121640, "end": 126600, "text": "Himalayan groove, feel it in your feet,", "index": 31}, {"start": 126920, "end": 130000, "text": "Electronic beats mixed with mountain heat.", "index": 32}, {"start": 131080, "end": 134760, "text": "Dance like the rivers, wild and sweet,", "index": 33}, {"start": 135920, "end": 139560, "text": "This Nepali rhythm can’t be beat!", "index": 34}]',
    conversion_status: "SUCCESS",
    publishing_status: "PUBLIC",
    conversion_type: "MUSIC_AI",
    play_count: 0,
    like_count: 0,
    file_output_0:
      "https://lalals.s3.amazonaws.com/conversions/standard/ea418f75-f2e7-4eb0-960b-552e4fec54e6/ea418f75-f2e7-4eb0-960b-552e4fec54e6.mp3",
    file_output_0_hq: "https://lalals.s3.amazonaws.com/",
    file_output_high_quality: "https://lalals.s3.amazonaws.com/",
    file_output_hls: "",
    file_output_vocals: null,
    file_output_vocals_hq: null,
    file_output_instrumental: null,
    file_output_instrumental_hq: null,
    file_output_other: null,
    file_output_other_hq: null,
    file_output_piano: null,
    file_output_piano_hq: null,
    file_output_guitar: null,
    file_output_guitar_hq: null,
    file_output_bass: null,
    file_output_bass_hq: null,
    file_output_drums: null,
    file_output_drums_hq: null,
    is_extracting_vocals: false,
    user: {
      id: "36384889-489c-44c6-9b25-289a95a1be9d",
      created_at: "2026-02-19T19:08:49.497Z",
      username: "yitek82056",
      display_name: "Test",
      image: null,
      image_thumbnail: null,
      total_followers: 0,
      client_plan_identifier: "FREE",
      client_plan_group: "FREE",
      bio: null,
      is_followed_by_requester: false,
      total_likes_received: 0,
      total_generations: 5,
    },
    bpm: null,
    generation_eta: 91,
    dominant_key: "",
    prompt_identifier: "78d8c49b-e085-4baf-bcaf-e32cdbfe7ae1",
    text_result: null,
    version_string: "Version 2",
    comment_count_total: 0,
    pending_comment_count: 0,
    is_liked_by_user: false,
    is_new: true,
    queue_number: 0,
    is_vocals_ready: false,
    is_instrumental_ready: false,
    is_generated_via_tool: false,
    available_downloads: ["FULL_SONG"],
    featured_request_status: null,
    owner_feedback_tag: null,
    owner_feedback_message: null,
  },
  {
    id: "24badae0-2bf9-47c7-b1c9-abd535154614",
    user_id: "36384889-489c-44c6-9b25-289a95a1be9d",
    created_at: "2026-02-20T03:29:12.508Z",
    is_instrumental: false,
    image_custom:
      "https://lalals.s3.amazonaws.com/GenImages/ff821b2c-53d0-45a5-803c-b7bb31cf17d0.jpg",
    image_custom_thumbnail:
      "https://lalals.s3.amazonaws.com/GenImages/ff821b2c-53d0-45a5-803c-b7bb31cf17d0_thumbnail.jpg",
    input_prompt: "nepali sattire",
    audio_length_ms: 194676,
    title: "The Satirical Echo of the world",
    lyrics_output:
      "Intro]\n[Madal drum solo starts with a heavy electronic sub-bass kick]\n[Sharp Sarangi melody plays a fast, repetitive hook]\n(हो हो!)\n(हेर मलाई!)\n\n[Verse 1]\nबजारको नयाँ क्रिम किनेर ल्याएँ\nअनुहारमा बाक्लो लेप मैले दलेँ\nहिजोसम्म त म अलि कालो थिएँ\nआज त म विदेशी जस्तै भएँ\n(को हो यो?)\nपुरानो म त कता हराएछ\nनयाँ यो छालाले सबैलाई जितेछ\n\n[Pre-Chorus]\nसूर्यको किरण देखि डराउँछु म त\nकालो छाता ओढेर मात्रै हिँड्छु म त\n(सेतो!)\n(एकदम सेतो!)\n\n[Chorus]\nम त गोरो, म कति राम्रो\nसबैको आँखा अब मतिरै हुन्छ\nकालो छालाको यहाँ कामै छैन\nचम्किलो मेरो यो नयाँ अवतार\nहेर मलाई, म त कति सफा!\n(गो-गो-गोरो!)\n\n[Verse 2]\nपुरानो संस्कृति र भेष भुलेँ\nविदेशी पाउडरमा म त झुम्मिएँ\nछिमेकीले मलाई चिन्नै छाडे\nनयाँ रुपको अर्कै रवाफ छ यहाँ\nचिउँडो अलि माथि, आँखामा घमण्ड\nबाटोमा हिँड्दा म नै ठालु जस्तो\n\n[Pre-Chorus]\nसूर्यको किरण देखि डराउँछु म त\nकालो छाता ओढेर मात्रै हिँड्छु म त\n(सेतो!)\n(एकदम सेतो!)\n\n[Chorus]\nम त गोरो, म कति राम्रो\nसबैको आँखा अब मतिरै हुन्छ\nकालो छालाको यहाँ कामै छैन\nचम्किलो मेरो यो नयाँ अवतार\nहेर मलाई, म त कति सफा!\n\n[Bridge]\n[The music slows down, heavy bass pulses]\nमन भित्र जस्तो भए नि के भो र?\nबाहिर त टल्किएको हुनुपर्छ\nसक्छौ भने मलाई चिनेर देखाऊ\nयो नक्कली रंगमा म नै हराएँ\n(हराएँ!)\n(म हराएँ!)\nसक्छौ भने अब छोएर देखाऊ\n\n[Chorus]\nम त गोरो, म कति राम्रो\nसबैको आँखा अब मतिरै हुन्छ\nकालो छालाको यहाँ कामै छैन\nचम्किलो मेरो यो नयाँ अवतार\nहेर मलाई, म त कति सफा!\n(गो-गो-गोरो!)\n\n[Outro]\n[Madal and Sarangi reach a frantic peak]\nपाउडर",
    lyrics_output_timestamped:
      '[{"index": 0, "text": "[Intro]", "start": 743, "end": 743}, {"index": 1, "text": "[Madal drum solo starts with a heavy electronic sub-bass kick]", "start": 743, "end": 743}, {"index": 2, "text": "[Sharp Sarangi melody plays a fast, repetitive hook]", "start": 743, "end": 743}, {"index": 3, "text": "(\ह\ो \ह\ो!)", "start": 743, "end": 13374}, {"index": 4, "text": "(\ह\े\र \म\ल\ा\ई!)", "start": 13374, "end": 23034}, {"index": 5, "text": "[Verse 1]", "start": 23034, "end": 27492}, {"index": 6, "text": "\ब\ज\ा\र\क\ो \न\य\ा\ँ \क\्\र\ि\म \क\ि\न\े\र \ल\्\य\ा\ए\ँ", "start": 28235, "end": 30464}, {"index": 7, "text": "\अ\न\ु\ह\ा\र\म\ा \ब\ा\क\्\ल\ो \ल\े\प \म\ै\ल\े \द\ल\े\ँ", "start": 30464, "end": 32693}, {"index": 8, "text": "\ह\ि\ज\ो\स\म\्\म \त \म \अ\ल\ि \क\ा\ल\ो \थ\ि\ए\ँ", "start": 32693, "end": 34922}, {"index": 9, "text": "\आ\ज \त \म \व\ि\द\े\श\ी \ज\स\्\त\ै \भ\ए\ँ", "start": 35665, "end": 37151}, {"index": 10, "text": "(\क\ो \ह\ो \य\ो?)", "start": 37151, "end": 39381}, {"index": 11, "text": "\प\ु\र\ा\न\ो \म \त \क\त\ा \ह\र\ा\ए\छ", "start": 39381, "end": 41610}, {"index": 12, "text": "\न\य\ा\ँ \य\ो \छ\ा\ल\ा\ल\े \स\ब\ै\ल\ा\ई \ज\ि\त\े\छ", "start": 41610, "end": 46068}, {"index": 13, "text": "[Pre-Chorus]", "start": 46068, "end": 46068}, {"index": 14, "text": "\स\ू\र\्\य\क\ो \क\ि\र\ण \द\े\ख\ि \ड\र\ा\उ\ँ\छ\ु \म \त", "start": 46811, "end": 49783}, {"index": 15, "text": "\क\ा\ल\ो \छ\ा\त\ा \ओ\ढ\े\र \म\ा\त\्\र\ै \ह\ि\ँ\ड\्\छ\ु \म \त", "start": 51269, "end": 54241}, {"index": 16, "text": "(\स\े\त\ो!)", "start": 54984, "end": 54984}, {"index": 17, "text": "(\ए\क\द\म \स\े\त\ो!)", "start": 54984, "end": 54984}, {"index": 18, "text": "[Chorus]", "start": 54984, "end": 55727}, {"index": 19, "text": "\म \त \ग\ो\र\ो, \म \क\त\ि \र\ा\म\्\र\ो", "start": 55727, "end": 57957}, {"index": 20, "text": "\स\ब\ै\क\ो \आ\ँ\ख\ा \अ\ब \म\त\ि\र\ै \ह\ु\न\्\छ", "start": 57957, "end": 59443}, {"index": 21, "text": "\क\ा\ल\ो \छ\ा\ल\ा\क\ो \य\ह\ा\ँ \क\ा\म\ै \छ\ै\न", "start": 60186, "end": 62415}, {"index": 22, "text": "\च\म\्\क\ि\ल\ो \म\े\र\ो \य\ो \न\य\ा\ँ \अ\व\त\ा\र", "start": 62415, "end": 64644}, {"index": 23, "text": "\ह\े\र \म\ल\ा\ई, \म \त \क\त\ि \स\फ\ा!", "start": 64644, "end": 67616}, {"index": 24, "text": "(\ग\ो-\ग\ो-\ग\ो\र\ो!)", "start": 67616, "end": 72074}, {"index": 25, "text": "[Verse 2]", "start": 72074, "end": 72074}, {"index": 26, "text": "\प\ु\र\ा\न\ो \स\ं\स\्\क\ृ\त\ि \र \भ\े\ष \भ\ु\ल\े\ँ", "start": 76532, "end": 79505}, {"index": 27, "text": "\व\ि\द\े\श\ी \प\ा\उ\ड\र\म\ा \म \त \झ\ु\म\्\म\ि\ए\ँ", "start": 79505, "end": 81734}, {"index": 28, "text": "\छ\ि\म\े\क\ी\ल\े \म\ल\ा\ई \च\ि\न\्\न\ै \छ\ा\ड\े", "start": 81734, "end": 83963}, {"index": 29, "text": "\न\य\ा\ँ \र\ु\प\क\ो \अ\र\्\क\ै \र\व\ा\फ \छ \य\ह\ा\ँ", "start": 84706, "end": 86192}, {"index": 30, "text": "\च\ि\उ\ँ\ड\ो \अ\ल\ि \म\ा\थ\ि, \आ\ँ\ख\ा\म\ा \घ\म\ण\्\ड", "start": 86935, "end": 90650}, {"index": 31, "text": "\ब\ा\ट\ो\म\ा \ह\ि\ँ\ड\्\द\ा \म \न\ै \ठ\ा\ल\ु \ज\स\्\त\ो", "start": 91393, "end": 95108}, {"index": 32, "text": "[Pre-Chorus]", "start": 95108, "end": 95851}, {"index": 33, "text": "\स\ू\र\्\य\क\ो \क\ि\र\ण \द\े\ख\ि \ड\र\ा\उ\ँ\छ\ु \म \त", "start": 95851, "end": 98824}, {"index": 34, "text": "\क\ा\ल\ो \छ\ा\त\ा \ओ\ढ\े\र \म\ा\त\्\र\ै \ह\ि\ँ\ड\्\छ\ु \म \त", "start": 99567, "end": 103282}, {"index": 35, "text": "(\स\े\त\ो!)", "start": 103282, "end": 104025}, {"index": 36, "text": "(\ए\क\द\म \स\े\त\ो!)", "start": 104025, "end": 104025}, {"index": 37, "text": "[Chorus]", "start": 104025, "end": 104025}, {"index": 38, "text": "\म \त \ग\ो\र\ो, \म \क\त\ि \र\ा\म\्\र\ो", "start": 104768, "end": 106254}, {"index": 39, "text": "\स\ब\ै\क\ो \आ\ँ\ख\ा \अ\ब \म\त\ि\र\ै \ह\ु\न\्\छ", "start": 106254, "end": 109226}, {"index": 40, "text": "\क\ा\ल\ो \छ\ा\ल\ा\क\ो \य\ह\ा\ँ \क\ा\म\ै \छ\ै\न", "start": 109226, "end": 111455}, {"index": 41, "text": "\च\म\्\क\ि\ल\ो \म\े\र\ो \य\ो \न\य\ा\ँ \अ\व\त\ा\र", "start": 111455, "end": 113684}, {"index": 42, "text": "\ह\े\र \म\ल\ा\ई, \म \त \क\त\ि \स\फ\ा!", "start": 113684, "end": 120372}, {"index": 43, "text": "[Bridge]", "start": 120372, "end": 123344}, {"index": 44, "text": "[The music slows down, heavy bass pulses]", "start": 123344, "end": 134489}, {"index": 45, "text": "\म\न \भ\ि\त\्\र \ज\स\्\त\ो \भ\ए \न\ि \क\े \भ\ो \र?", "start": 134489, "end": 139691}, {"index": 46, "text": "\ब\ा\ह\ि\र \त \ट\ल\्\क\ि\ए\क\ो \ह\ु\न\ु\प\र\्\छ", "start": 139691, "end": 143406}, {"index": 47, "text": "\स\क\्\छ\ौ \भ\न\े \म\ल\ा\ई \च\ि\न\े\र \द\े\ख\ा\ऊ", "start": 144149, "end": 148607}, {"index": 48, "text": "\य\ो \न\क\्\क\ल\ी \र\ं\ग\म\ा \म \न\ै \ह\र\ा\ए\ँ", "start": 148607, "end": 153808}, {"index": 49, "text": "(\ह\र\ा\ए\ँ!)", "start": 154552, "end": 155295}, {"index": 50, "text": "(\म \ह\र\ा\ए\ँ!)", "start": 155295, "end": 158267}, {"index": 51, "text": "\स\क\्\छ\ौ \भ\न\े \अ\ब \छ\ो\ए\र \द\े\ख\ा\ऊ", "start": 159010, "end": 161239}, {"index": 52, "text": "[Chorus]", "start": 161982, "end": 162725}, {"index": 53, "text": "\म \त \ग\ो\र\ो, \म \क\त\ि \र\ा\म\्\र\ो", "start": 162725, "end": 164954}, {"index": 54, "text": "\स\ब\ै\क\ो \आ\ँ\ख\ा \अ\ब \म\त\ि\र\ै \ह\ु\न\्\छ", "start": 164954, "end": 167183}, {"index": 55, "text": "\क\ा\ल\ो \छ\ा\ल\ा\क\ो \य\ह\ा\ँ \क\ा\म\ै \छ\ै\न", "start": 167183, "end": 170155}, {"index": 56, "text": "\च\म\्\क\ि\ल\ो \म\े\र\ो \य\ो \न\य\ा\ँ \अ\व\त\ा\र", "start": 170155, "end": 173127}, {"index": 57, "text": "\ह\े\र \म\ल\ा\ई, \म \त \क\त\ि \स\फ\ा!", "start": 173127, "end": 174614}, {"index": 58, "text": "(\ग\ो-\ग\ो-\ग\ो\र\ो!)", "start": 174614, "end": 194676}, {"index": 59, "text": "[Outro]", "start": 227369, "end": 194676}, {"index": 60, "text": "[Madal and Sarangi reach a frantic peak]", "start": 227369, "end": 194676}, {"index": 61, "text": "\प\ा\उ\ड\र", "start": 232571, "end": 194676}]',
    conversion_status: "SUCCESS",
    publishing_status: "PRIVATE",
    conversion_type: "MUSIC_AI",
    play_count: 3,
    like_count: 0,
    file_output_0:
      "https://lalals.s3.amazonaws.com/conversions/standard/24badae0-2bf9-47c7-b1c9-abd535154614/24badae0-2bf9-47c7-b1c9-abd535154614.mp3",
    file_output_0_hq: "https://lalals.s3.amazonaws.com/",
    file_output_high_quality: "https://lalals.s3.amazonaws.com/",
    file_output_hls: "",
    file_output_vocals: null,
    file_output_vocals_hq: null,
    file_output_instrumental: null,
    file_output_instrumental_hq: null,
    file_output_other: null,
    file_output_other_hq: null,
    file_output_piano: null,
    file_output_piano_hq: null,
    file_output_guitar: null,
    file_output_guitar_hq: null,
    file_output_bass: null,
    file_output_bass_hq: null,
    file_output_drums: null,
    file_output_drums_hq: null,
    is_extracting_vocals: false,
    user: {
      id: "36384889-489c-44c6-9b25-289a95a1be9d",
      created_at: "2026-02-19T19:08:49.497Z",
      username: "yitek82056",
      display_name: "Test",
      image: null,
      image_thumbnail: null,
      total_followers: 0,
      client_plan_identifier: "FREE",
      client_plan_group: "FREE",
      bio: null,
      is_followed_by_requester: false,
      total_likes_received: 0,
      total_generations: 5,
    },
    bpm: null,
    generation_eta: 101,
    dominant_key: "",
    prompt_identifier: "2ea9b71f-e0cc-4ec5-8465-75e158d4e55e",
    text_result: null,
    version_string: "Version 1",
    comment_count_total: 3,
    pending_comment_count: 0,
    is_liked_by_user: false,
    is_new: true,
    queue_number: 25413,
    is_vocals_ready: false,
    is_instrumental_ready: false,
    is_generated_via_tool: false,
    available_downloads: ["FULL_SONG"],
    featured_request_status: null,
    owner_feedback_tag: null,
    owner_feedback_message: null,
  },
  {
    id: "2ea9b71f-e0cc-4ec5-8465-75e158d4e55e",
    user_id: "36384889-489c-44c6-9b25-289a95a1be9d",
    created_at: "2026-02-20T03:29:11.508Z",
    is_instrumental: false,
    image_custom:
      "https://lalals.s3.amazonaws.com/GenImages/ff821b2c-53d0-45a5-803c-b7bb31cf17d0.jpg",
    image_custom_thumbnail:
      "https://lalals.s3.amazonaws.com/GenImages/ff821b2c-53d0-45a5-803c-b7bb31cf17d0_thumbnail.jpg",
    input_prompt: "nepali sattire",
    audio_length_ms: 194676,
    title: "The Satirical Echo",
    lyrics_output:
      "Intro]\n[Madal drum solo starts with a heavy electronic sub-bass kick]\n[Sharp Sarangi melody plays a fast, repetitive hook]\n(हो हो!)\n(हेर मलाई!)\n\n[Verse 1]\nबजारको नयाँ क्रिम किनेर ल्याएँ\nअनुहारमा बाक्लो लेप मैले दलेँ\nहिजोसम्म त म अलि कालो थिएँ\nआज त म विदेशी जस्तै भएँ\n(को हो यो?)\nपुरानो म त कता हराएछ\nनयाँ यो छालाले सबैलाई जितेछ\n\n[Pre-Chorus]\nसूर्यको किरण देखि डराउँछु म त\nकालो छाता ओढेर मात्रै हिँड्छु म त\n(सेतो!)\n(एकदम सेतो!)\n\n[Chorus]\nम त गोरो, म कति राम्रो\nसबैको आँखा अब मतिरै हुन्छ\nकालो छालाको यहाँ कामै छैन\nचम्किलो मेरो यो नयाँ अवतार\nहेर मलाई, म त कति सफा!\n(गो-गो-गोरो!)\n\n[Verse 2]\nपुरानो संस्कृति र भेष भुलेँ\nविदेशी पाउडरमा म त झुम्मिएँ\nछिमेकीले मलाई चिन्नै छाडे\nनयाँ रुपको अर्कै रवाफ छ यहाँ\nचिउँडो अलि माथि, आँखामा घमण्ड\nबाटोमा हिँड्दा म नै ठालु जस्तो\n\n[Pre-Chorus]\nसूर्यको किरण देखि डराउँछु म त\nकालो छाता ओढेर मात्रै हिँड्छु म त\n(सेतो!)\n(एकदम सेतो!)\n\n[Chorus]\nम त गोरो, म कति राम्रो\nसबैको आँखा अब मतिरै हुन्छ\nकालो छालाको यहाँ कामै छैन\nचम्किलो मेरो यो नयाँ अवतार\nहेर मलाई, म त कति सफा!\n\n[Bridge]\n[The music slows down, heavy bass pulses]\nमन भित्र जस्तो भए नि के भो र?\nबाहिर त टल्किएको हुनुपर्छ\nसक्छौ भने मलाई चिनेर देखाऊ\nयो नक्कली रंगमा म नै हराएँ\n(हराएँ!)\n(म हराएँ!)\nसक्छौ भने अब छोएर देखाऊ\n\n[Chorus]\nम त गोरो, म कति राम्रो\nसबैको आँखा अब मतिरै हुन्छ\nकालो छालाको यहाँ कामै छैन\nचम्किलो मेरो यो नयाँ अवतार\nहेर मलाई, म त कति सफा!\n(गो-गो-गोरो!)\n\n[Outro]\n[Madal and Sarangi reach a frantic peak]\nपाउडर",
    lyrics_output_timestamped:
      '[{"index": 0, "text": "[Intro]", "start": 2229, "end": 2229}, {"index": 1, "text": "[Madal drum solo starts with a heavy electronic sub-bass kick]", "start": 4458, "end": 4458}, {"index": 2, "text": "[Sharp Sarangi melody plays a fast, repetitive hook]", "start": 4458, "end": 4458}, {"index": 3, "text": "(\ह\ो \ह\ो!)", "start": 4458, "end": 4458}, {"index": 4, "text": "(\ह\े\र \म\ल\ा\ई!)", "start": 4458, "end": 5201}, {"index": 5, "text": "[Verse 1]", "start": 9659, "end": 9659}, {"index": 6, "text": "\ब\ज\ा\र\क\ो \न\य\ा\ँ \क\्\र\ि\म \क\ि\न\े\र \ल\्\य\ा\ए\ँ", "start": 9659, "end": 12631}, {"index": 7, "text": "\अ\न\ु\ह\ा\र\म\ा \ब\ा\क\्\ल\ो \ल\े\प \म\ै\ल\े \द\ल\े\ँ", "start": 12631, "end": 14860}, {"index": 8, "text": "\ह\ि\ज\ो\स\म\्\म \त \म \अ\ल\ि \क\ा\ल\ो \थ\ि\ए\ँ", "start": 14860, "end": 17832}, {"index": 9, "text": "\आ\ज \त \म \व\ि\द\े\श\ी \ज\स\्\त\ै \भ\ए\ँ", "start": 17832, "end": 20062}, {"index": 10, "text": "(\क\ो \ह\ो \य\ो?)", "start": 20062, "end": 20805}, {"index": 11, "text": "\प\ु\र\ा\न\ो \म \त \क\त\ा \ह\र\ा\ए\छ", "start": 20805, "end": 22291}, {"index": 12, "text": "\न\य\ा\ँ \य\ो \छ\ा\ल\ा\ल\े \स\ब\ै\ल\ा\ई \ज\ि\त\े\छ", "start": 22291, "end": 24520}, {"index": 13, "text": "[Pre-Chorus]", "start": 24520, "end": 25263}, {"index": 14, "text": "\स\ू\र\्\य\क\ो \क\ि\र\ण \द\े\ख\ि \ड\र\ा\उ\ँ\छ\ु \म \त", "start": 25263, "end": 27492}, {"index": 15, "text": "\क\ा\ल\ो \छ\ा\त\ा \ओ\ढ\े\र \म\ा\त\्\र\ै \ह\ि\ँ\ड\्\छ\ु \म \त", "start": 27492, "end": 28978}, {"index": 16, "text": "(\स\े\त\ो!)", "start": 29721, "end": 30464}, {"index": 17, "text": "(\ए\क\द\म \स\े\त\ो!)", "start": 30464, "end": 31950}, {"index": 18, "text": "[Chorus]", "start": 31950, "end": 31950}, {"index": 19, "text": "\म \त \ग\ो\र\ो, \म \क\त\ि \र\ा\म\्\र\ो", "start": 31950, "end": 36408}, {"index": 20, "text": "\स\ब\ै\क\ो \आ\ँ\ख\ा \अ\ब \म\त\ि\र\ै \ह\ु\न\्\छ", "start": 36408, "end": 40124}, {"index": 21, "text": "\क\ा\ल\ो \छ\ा\ल\ा\क\ो \य\ह\ा\ँ \क\ा\म\ै \छ\ै\न", "start": 41610, "end": 45325}, {"index": 22, "text": "\च\म\्\क\ि\ल\ो \म\े\र\ो \य\ो \न\य\ा\ँ \अ\व\त\ा\र", "start": 46811, "end": 49040}, {"index": 23, "text": "\ह\े\र \म\ल\ा\ई, \म \त \क\त\ि \स\फ\ा!", "start": 49040, "end": 56470}, {"index": 24, "text": "(\ग\ो-\ग\ो-\ग\ो\र\ो!)", "start": 56470, "end": 57957}, {"index": 25, "text": "[Verse 2]", "start": 58700, "end": 61672}, {"index": 26, "text": "\प\ु\र\ा\न\ो \स\ं\स\्\क\ृ\त\ि \र \भ\े\ष \भ\ु\ल\े\ँ", "start": 62415, "end": 66130}, {"index": 27, "text": "\व\ि\द\े\श\ी \प\ा\उ\ड\र\म\ा \म \त \झ\ु\म\्\म\ि\ए\ँ", "start": 66130, "end": 67616}, {"index": 28, "text": "\छ\ि\म\े\क\ी\ल\े \म\ल\ा\ई \च\ि\न\्\न\ै \छ\ा\ड\े", "start": 68359, "end": 70588}, {"index": 29, "text": "\न\य\ा\ँ \र\ु\प\क\ो \अ\र\्\क\ै \र\व\ा\फ \छ \य\ह\ा\ँ", "start": 70588, "end": 72817}, {"index": 30, "text": "\च\ि\उ\ँ\ड\ो \अ\ल\ि \म\ा\थ\ि, \आ\ँ\ख\ा\म\ा \घ\म\ण\्\ड", "start": 72817, "end": 75789}, {"index": 31, "text": "\ब\ा\ट\ो\म\ा \ह\ि\ँ\ड\्\द\ा \म \न\ै \ठ\ा\ल\ु \ज\स\्\त\ो", "start": 75789, "end": 78019}, {"index": 32, "text": "[Pre-Chorus]", "start": 78019, "end": 78019}, {"index": 33, "text": "\स\ू\र\्\य\क\ो \क\ि\र\ण \द\े\ख\ि \ड\र\ा\उ\ँ\छ\ु \म \त", "start": 78019, "end": 80248}, {"index": 34, "text": "\क\ा\ल\ो \छ\ा\त\ा \ओ\ढ\े\र \म\ा\त\्\र\ै \ह\ि\ँ\ड\्\छ\ु \म \त", "start": 80248, "end": 82477}, {"index": 35, "text": "(\स\े\त\ो!)", "start": 82477, "end": 83963}, {"index": 36, "text": "(\ए\क\द\म \स\े\त\ो!)", "start": 83963, "end": 85449}, {"index": 37, "text": "[Chorus]", "start": 85449, "end": 85449}, {"index": 38, "text": "\म \त \ग\ो\र\ो, \म \क\त\ि \र\ा\म\्\र\ो", "start": 85449, "end": 89164}, {"index": 39, "text": "\स\ब\ै\क\ो \आ\ँ\ख\ा \अ\ब \म\त\ि\र\ै \ह\ु\न\्\छ", "start": 89164, "end": 93622}, {"index": 40, "text": "\क\ा\ल\ो \छ\ा\ल\ा\क\ो \य\ह\ा\ँ \क\ा\म\ै \छ\ै\न", "start": 94365, "end": 99567}, {"index": 41, "text": "\च\म\्\क\ि\ल\ो \म\े\र\ो \य\ो \न\य\ा\ँ \अ\व\त\ा\र", "start": 100310, "end": 104025}, {"index": 42, "text": "\ह\े\र \म\ल\ा\ई, \म \त \क\त\ि \स\फ\ा!", "start": 104025, "end": 109226}, {"index": 43, "text": "[Bridge]", "start": 109226, "end": 113684}, {"index": 44, "text": "[The music slows down, heavy bass pulses]", "start": 113684, "end": 115914}, {"index": 45, "text": "\म\न \भ\ि\त\्\र \ज\स\्\त\ो \भ\ए \न\ि \क\े \भ\ो \र?", "start": 115914, "end": 119629}, {"index": 46, "text": "\ब\ा\ह\ि\र \त \ट\ल\्\क\ि\ए\क\ो \ह\ु\न\ु\प\र\्\छ", "start": 120372, "end": 124087}, {"index": 47, "text": "\स\क\्\छ\ौ \भ\न\े \म\ल\ा\ई \च\ि\न\े\र \द\े\ख\ा\ऊ", "start": 125573, "end": 129288}, {"index": 48, "text": "\य\ो \न\क\्\क\ल\ी \र\ं\ग\म\ा \म \न\ै \ह\र\ा\ए\ँ", "start": 130031, "end": 134489}, {"index": 49, "text": "(\ह\र\ा\ए\ँ!)", "start": 135976, "end": 139691}, {"index": 50, "text": "(\म \ह\र\ा\ए\ँ!)", "start": 139691, "end": 141177}, {"index": 51, "text": "\स\क\्\छ\ौ \भ\न\े \अ\ब \छ\ो\ए\र \द\े\ख\ा\ऊ", "start": 141177, "end": 143406}, {"index": 52, "text": "[Chorus]", "start": 144892, "end": 150836}, {"index": 53, "text": "\म \त \ग\ो\र\ो, \म \क\त\ि \र\ा\म\्\र\ो", "start": 150836, "end": 153808}, {"index": 54, "text": "\स\ब\ै\क\ो \आ\ँ\ख\ा \अ\ब \म\त\ि\र\ै \ह\ु\न\्\छ", "start": 155295, "end": 159753}, {"index": 55, "text": "\क\ा\ल\ो \छ\ा\ल\ा\क\ो \य\ह\ा\ँ \क\ा\म\ै \छ\ै\न", "start": 160496, "end": 164954}, {"index": 56, "text": "\च\म\्\क\ि\ल\ो \म\े\र\ो \य\ो \न\य\ा\ँ \अ\व\त\ा\र", "start": 164954, "end": 165697}, {"index": 57, "text": "\ह\े\र \म\ल\ा\ई, \म \त \क\त\ि \स\फ\ा!", "start": 165697, "end": 172384}, {"index": 58, "text": "(\ग\ो-\ग\ो-\ग\ो\र\ो!)", "start": 173127, "end": 180558}, {"index": 59, "text": "[Outro]", "start": 182044, "end": 182044}, {"index": 60, "text": "[Madal and Sarangi reach a frantic peak]", "start": 182044, "end": 194676}, {"index": 61, "text": "\प\ा\उ\ड\र", "start": 208050, "end": 194676}]',
    conversion_status: "SUCCESS",
    publishing_status: "PRIVATE",
    conversion_type: "MUSIC_AI",
    play_count: 2,
    like_count: 0,
    file_output_0:
      "https://lalals.s3.amazonaws.com/conversions/standard/2ea9b71f-e0cc-4ec5-8465-75e158d4e55e/2ea9b71f-e0cc-4ec5-8465-75e158d4e55e.mp3",
    file_output_0_hq: "https://lalals.s3.amazonaws.com/",
    file_output_high_quality: "https://lalals.s3.amazonaws.com/",
    file_output_hls: "",
    file_output_vocals: null,
    file_output_vocals_hq: null,
    file_output_instrumental: null,
    file_output_instrumental_hq: null,
    file_output_other: null,
    file_output_other_hq: null,
    file_output_piano: null,
    file_output_piano_hq: null,
    file_output_guitar: null,
    file_output_guitar_hq: null,
    file_output_bass: null,
    file_output_bass_hq: null,
    file_output_drums: null,
    file_output_drums_hq: null,
    is_extracting_vocals: false,
    user: {
      id: "36384889-489c-44c6-9b25-289a95a1be9d",
      created_at: "2026-02-19T19:08:49.497Z",
      username: "yitek82056",
      display_name: "Test",
      image: null,
      image_thumbnail: null,
      total_followers: 0,
      client_plan_identifier: "FREE",
      client_plan_group: "FREE",
      bio: null,
      is_followed_by_requester: false,
      total_likes_received: 0,
      total_generations: 5,
    },
    bpm: null,
    generation_eta: 101,
    dominant_key: "",
    prompt_identifier: "2ea9b71f-e0cc-4ec5-8465-75e158d4e55e",
    text_result: null,
    version_string: "Version 2",
    comment_count_total: 0,
    pending_comment_count: 0,
    is_liked_by_user: false,
    is_new: true,
    queue_number: 25413,
    is_vocals_ready: false,
    is_instrumental_ready: false,
    is_generated_via_tool: false,
    available_downloads: ["FULL_SONG"],
    featured_request_status: null,
    owner_feedback_tag: null,
    owner_feedback_message: null,
  },
  {
    id: "92deb404-f5a5-488a-b657-e09c020d4ea7",
    user_id: "36384889-489c-44c6-9b25-289a95a1be9d",
    created_at: "2026-02-20T03:25:25.552Z",
    is_instrumental: false,
    image_custom:
      "https://lalals.s3.amazonaws.com/GenImages/1b0198ee-bf93-4954-8bfb-c5fd9f538d27.jpg",
    image_custom_thumbnail:
      "https://lalals.s3.amazonaws.com/GenImages/1b0198ee-bf93-4954-8bfb-c5fd9f538d27_thumbnail.jpg",
    input_prompt: "nepali song",
    audio_length_ms: 222169,
    title: "Sundar Sapana",
    lyrics_output:
      "Intro]\n[Slow, intricate fingerpicked acoustic guitar starts, joined by the mournful breath of a Bansuri flute]\n\n[Verse 1]\nI leave the stone gate before the sun finds the eaves.\nThe wet grass clings to my thick woollen wrap.\nDown in the Besi, the river is a silver thread,\nSewn into the dark, folded skin of the earth.\nThe madal’s rhythm fades behind the first ridge.\n(The valley sleeps, the valley stays)\n\n[Refrain]\nThe peak stands silent, a white-crowned king.\nBut my breath belongs where the woodsmoke rises.\nAbove the clouds, the air is thin and sharp.\nBelow the pines, the hearth is always burning.\n\n[Verse 2]\nAt the Chautari, I rest my heavy wicker basket.\nThe wind here tastes of ice and ancient stone.\nMy mother’s hands are stained with turmeric and soil.\nI see her face in the shape of the passing clouds.\nShe stirs the copper pot as the shadows lengthen.\n(Warmth of the clay, scent of the grain)\n\n[Instrumental Break]\n[The Sarangi takes the melody, weeping and soaring, backed by a deep, resonant Cello]\n\n[Verse 3]\nThe prayer flags snap like dry birch branches.\nThey carry my longing to the top of the world.\nThe higher I climb, the smaller the village becomes.\nA handful of grain scattered on a green cloth.\nI am a guest of the heights, but a son of the valley.\n(A son of the dust, a son of the rain)\n\n[Refrain]\nThe peak stands silent, a white-crowned king.\nBut my breath belongs where the woodsmoke rises.\nAbove the clouds, the air is thin and sharp.\nBelow the pines, the hearth is always burning.\n\n[Outro]\n[The Bansuri flute mimics a distant bird call]\nThe snow begins to fall on the rhododendron leaves.\nThe path goes up, but the heart looks back.\n[Final soft guitar chord rings out and slowly decays]",
    lyrics_output_timestamped:
      '[{"index": 0, "text": "[Intro]", "start": 743, "end": 743}, {"index": 1, "text": "[Slow, intricate fingerpicked acoustic guitar starts, joined by the mournful breath of a Bansuri flute]", "start": 743, "end": 5201}, {"index": 2, "text": "[Verse 1]", "start": 5201, "end": 26006}, {"index": 3, "text": "I leave the stone gate before the sun finds the eaves.", "start": 26006, "end": 31950}, {"index": 4, "text": "The wet grass clings to my thick woollen wrap.", "start": 31950, "end": 35665}, {"index": 5, "text": "Down in the Besi, the river is a silver thread,", "start": 38638, "end": 43096}, {"index": 6, "text": "Sewn into the dark, folded skin of the earth.", "start": 43096, "end": 45325}, {"index": 7, "text": "The madal\’s rhythm fades behind the first ridge.", "start": 45325, "end": 49783}, {"index": 8, "text": "(The valley sleeps, the valley stays)", "start": 49783, "end": 52012}, {"index": 9, "text": "[Refrain]", "start": 52012, "end": 52012}, {"index": 10, "text": "The peak stands silent, a white-crowned king.", "start": 52012, "end": 57213}, {"index": 11, "text": "But my breath belongs where the woodsmoke rises.", "start": 57957, "end": 65387}, {"index": 12, "text": "Above the clouds, the air is thin and sharp.", "start": 65387, "end": 71331}, {"index": 13, "text": "Below the pines, the hearth is always burning.", "start": 71331, "end": 78762}, {"index": 14, "text": "[Verse 2]", "start": 78762, "end": 80248}, {"index": 15, "text": "At the Chautari, I rest my heavy wicker basket.", "start": 80248, "end": 84706}, {"index": 16, "text": "The wind here tastes of ice and ancient stone.", "start": 85449, "end": 91393}, {"index": 17, "text": "My mother\’s hands are stained with turmeric and soil.", "start": 92879, "end": 95851}, {"index": 18, "text": "I see her face in the shape of the passing clouds.", "start": 95851, "end": 98824}, {"index": 19, "text": "She stirs the copper pot as the shadows lengthen.", "start": 98824, "end": 101796}, {"index": 20, "text": "(Warmth of the clay, scent of the grain)", "start": 101796, "end": 104768}, {"index": 21, "text": "[Instrumental Break]", "start": 104768, "end": 110712}, {"index": 22, "text": "[The Sarangi takes the melody, weeping and soaring, backed by a deep, resonant Cello]", "start": 110712, "end": 135976}, {"index": 23, "text": "[Verse 3]", "start": 135976, "end": 139691}, {"index": 24, "text": "The prayer flags snap like dry birch branches.", "start": 139691, "end": 144149}, {"index": 25, "text": "They carry my longing to the top of the world.", "start": 145635, "end": 151579}, {"index": 26, "text": "The higher I climb, the smaller the village becomes.", "start": 151579, "end": 156781}, {"index": 27, "text": "A handful of grain scattered on a green cloth.", "start": 156781, "end": 158267}, {"index": 28, "text": "I am a guest of the heights, but a son of the valley.", "start": 158267, "end": 161982}, {"index": 29, "text": "(A son of the dust, a son of the rain)", "start": 162725, "end": 165697}, {"index": 30, "text": "[Refrain]", "start": 165697, "end": 165697}, {"index": 31, "text": "The peak stands silent, a white-crowned king.", "start": 165697, "end": 169412}, {"index": 32, "text": "But my breath belongs where the woodsmoke rises.", "start": 169412, "end": 176843}, {"index": 33, "text": "Above the clouds, the air is thin and sharp.", "start": 176843, "end": 183530}, {"index": 34, "text": "Below the pines, the hearth is always burning.", "start": 183530, "end": 190217}, {"index": 35, "text": "[Outro]", "start": 190217, "end": 192446}, {"index": 36, "text": "[The Bansuri flute mimics a distant bird call]", "start": 192446, "end": 207307}, {"index": 37, "text": "The snow begins to fall on the rhododendron leaves.", "start": 207307, "end": 213252}, {"index": 38, "text": "The path goes up, but the heart looks back.", "start": 213252, "end": 219196}, {"index": 39, "text": "[Final soft guitar chord rings out and slowly decays]", "start": 219196, "end": 222168}]',
    conversion_status: "SUCCESS",
    publishing_status: "PRIVATE",
    conversion_type: "MUSIC_AI",
    play_count: 0,
    like_count: 0,
    file_output_0:
      "https://lalals.s3.amazonaws.com/conversions/standard/92deb404-f5a5-488a-b657-e09c020d4ea7/92deb404-f5a5-488a-b657-e09c020d4ea7.mp3",
    file_output_0_hq: "https://lalals.s3.amazonaws.com/",
    file_output_high_quality: "https://lalals.s3.amazonaws.com/",
    file_output_hls: "",
    file_output_vocals: null,
    file_output_vocals_hq: null,
    file_output_instrumental: null,
    file_output_instrumental_hq: null,
    file_output_other: null,
    file_output_other_hq: null,
    file_output_piano: null,
    file_output_piano_hq: null,
    file_output_guitar: null,
    file_output_guitar_hq: null,
    file_output_bass: null,
    file_output_bass_hq: null,
    file_output_drums: null,
    file_output_drums_hq: null,
    is_extracting_vocals: false,
    user: {
      id: "36384889-489c-44c6-9b25-289a95a1be9d",
      created_at: "2026-02-19T19:08:49.497Z",
      username: "yitek82056",
      display_name: "Test",
      image: null,
      image_thumbnail: null,
      total_followers: 0,
      client_plan_identifier: "FREE",
      client_plan_group: "FREE",
      bio: null,
      is_followed_by_requester: false,
      total_likes_received: 0,
      total_generations: 5,
    },
    bpm: null,
    generation_eta: 98,
    dominant_key: "",
    prompt_identifier: "27a0a301-e8b4-4ca9-9d33-769331122fe5",
    text_result: null,
    version_string: "Version 1",
    comment_count_total: 0,
    pending_comment_count: 0,
    is_liked_by_user: false,
    is_new: true,
    queue_number: 25413,
    is_vocals_ready: false,
    is_instrumental_ready: false,
    is_generated_via_tool: false,
    available_downloads: ["FULL_SONG"],
    featured_request_status: null,
    owner_feedback_tag: null,
    owner_feedback_message: null,
  },
  {
    id: "27a0a301-e8b4-4ca9-9d33-769331122fe5",
    user_id: "36384889-489c-44c6-9b25-289a95a1be9d",
    created_at: "2026-02-20T03:25:24.552Z",
    is_instrumental: false,
    image_custom:
      "https://lalals.s3.amazonaws.com/GenImages/1b0198ee-bf93-4954-8bfb-c5fd9f538d27.jpg",
    image_custom_thumbnail:
      "https://lalals.s3.amazonaws.com/GenImages/1b0198ee-bf93-4954-8bfb-c5fd9f538d27_thumbnail.jpg",
    input_prompt: "nepali song",
    audio_length_ms: 233314,
    title: "Sundar Sapana",
    lyrics_output:
      "Intro]\n[Slow, intricate fingerpicked acoustic guitar starts, joined by the mournful breath of a Bansuri flute]\n\n[Verse 1]\nI leave the stone gate before the sun finds the eaves.\nThe wet grass clings to my thick woollen wrap.\nDown in the Besi, the river is a silver thread,\nSewn into the dark, folded skin of the earth.\nThe madal’s rhythm fades behind the first ridge.\n(The valley sleeps, the valley stays)\n\n[Refrain]\nThe peak stands silent, a white-crowned king.\nBut my breath belongs where the woodsmoke rises.\nAbove the clouds, the air is thin and sharp.\nBelow the pines, the hearth is always burning.\n\n[Verse 2]\nAt the Chautari, I rest my heavy wicker basket.\nThe wind here tastes of ice and ancient stone.\nMy mother’s hands are stained with turmeric and soil.\nI see her face in the shape of the passing clouds.\nShe stirs the copper pot as the shadows lengthen.\n(Warmth of the clay, scent of the grain)\n\n[Instrumental Break]\n[The Sarangi takes the melody, weeping and soaring, backed by a deep, resonant Cello]\n\n[Verse 3]\nThe prayer flags snap like dry birch branches.\nThey carry my longing to the top of the world.\nThe higher I climb, the smaller the village becomes.\nA handful of grain scattered on a green cloth.\nI am a guest of the heights, but a son of the valley.\n(A son of the dust, a son of the rain)\n\n[Refrain]\nThe peak stands silent, a white-crowned king.\nBut my breath belongs where the woodsmoke rises.\nAbove the clouds, the air is thin and sharp.\nBelow the pines, the hearth is always burning.\n\n[Outro]\n[The Bansuri flute mimics a distant bird call]\nThe snow begins to fall on the rhododendron leaves.\nThe path goes up, but the heart looks back.\n[Final soft guitar chord rings out and slowly decays]",
    lyrics_output_timestamped:
      '[{"index": 0, "text": "[Intro]", "start": 743, "end": 743}, {"index": 1, "text": "[Slow, intricate fingerpicked acoustic guitar starts, joined by the mournful breath of a Bansuri flute]", "start": 6687, "end": 20805}, {"index": 2, "text": "[Verse 1]", "start": 20805, "end": 22291}, {"index": 3, "text": "I leave the stone gate before the sun finds the eaves.", "start": 22291, "end": 28235}, {"index": 4, "text": "The wet grass clings to my thick woollen wrap.", "start": 28235, "end": 32693}, {"index": 5, "text": "Down in the Besi, the river is a silver thread,", "start": 35665, "end": 40124}, {"index": 6, "text": "Sewn into the dark, folded skin of the earth.", "start": 41610, "end": 46811}, {"index": 7, "text": "The madal\’s rhythm fades behind the first ridge.", "start": 46811, "end": 52755}, {"index": 8, "text": "(The valley sleeps, the valley stays)", "start": 52755, "end": 57957}, {"index": 9, "text": "[Refrain]", "start": 58700, "end": 60929}, {"index": 10, "text": "The peak stands silent, a white-crowned king.", "start": 60929, "end": 65387}, {"index": 11, "text": "But my breath belongs where the woodsmoke rises.", "start": 66873, "end": 73560}, {"index": 12, "text": "Above the clouds, the air is thin and sharp.", "start": 73560, "end": 78019}, {"index": 13, "text": "Below the pines, the hearth is always burning.", "start": 78019, "end": 86935}, {"index": 14, "text": "[Verse 2]", "start": 86935, "end": 103282}, {"index": 15, "text": "At the Chautari, I rest my heavy wicker basket.", "start": 103282, "end": 107740}, {"index": 16, "text": "The wind here tastes of ice and ancient stone.", "start": 108483, "end": 113684}, {"index": 17, "text": "My mother\’s hands are stained with turmeric and soil.", "start": 115170, "end": 121115}, {"index": 18, "text": "I see her face in the shape of the passing clouds.", "start": 121858, "end": 127059}, {"index": 19, "text": "She stirs the copper pot as the shadows lengthen.", "start": 127059, "end": 133003}, {"index": 20, "text": "(Warmth of the clay, scent of the grain)", "start": 133746, "end": 144892}, {"index": 21, "text": "[Instrumental Break]", "start": 144892, "end": 150836}, {"index": 22, "text": "[The Sarangi takes the melody, weeping and soaring, backed by a deep, resonant Cello]", "start": 150836, "end": 155295}, {"index": 23, "text": "[Verse 3]", "start": 155295, "end": 158267}, {"index": 24, "text": "The prayer flags snap like dry birch branches.", "start": 158267, "end": 162725}, {"index": 25, "text": "They carry my longing to the top of the world.", "start": 164954, "end": 170155}, {"index": 26, "text": "The higher I climb, the smaller the village becomes.", "start": 170155, "end": 176100}, {"index": 27, "text": "A handful of grain scattered on a green cloth.", "start": 176843, "end": 182787}, {"index": 28, "text": "I am a guest of the heights, but a son of the valley.", "start": 182787, "end": 187245}, {"index": 29, "text": "(A son of the dust, a son of the rain)", "start": 187988, "end": 193933}, {"index": 30, "text": "[Refrain]", "start": 194676, "end": 196162}, {"index": 31, "text": "The peak stands silent, a white-crowned king.", "start": 196162, "end": 202106}, {"index": 32, "text": "But my breath belongs where the woodsmoke rises.", "start": 202106, "end": 208793}, {"index": 33, "text": "Above the clouds, the air is thin and sharp.", "start": 208793, "end": 213995}, {"index": 34, "text": "Below the pines, the hearth is always burning.", "start": 213995, "end": 218453}, {"index": 35, "text": "[Outro]", "start": 218453, "end": 219196}, {"index": 36, "text": "[The Bansuri flute mimics a distant bird call]", "start": 219196, "end": 219939}, {"index": 37, "text": "The snow begins to fall on the rhododendron leaves.", "start": 219939, "end": 225883}, {"index": 38, "text": "The path goes up, but the heart looks back.", "start": 225883, "end": 231828}, {"index": 39, "text": "[Final soft guitar chord rings out and slowly decays]", "start": 231828, "end": 233314}]',
    conversion_status: "SUCCESS",
    publishing_status: "PRIVATE",
    conversion_type: "MUSIC_AI",
    play_count: 2,
    like_count: 0,
    file_output_0:
      "https://lalals.s3.amazonaws.com/conversions/standard/27a0a301-e8b4-4ca9-9d33-769331122fe5/27a0a301-e8b4-4ca9-9d33-769331122fe5.mp3",
    file_output_0_hq: "https://lalals.s3.amazonaws.com/",
    file_output_high_quality: "https://lalals.s3.amazonaws.com/",
    file_output_hls: "",
    file_output_vocals: null,
    file_output_vocals_hq: null,
    file_output_instrumental: null,
    file_output_instrumental_hq: null,
    file_output_other: null,
    file_output_other_hq: null,
    file_output_piano: null,
    file_output_piano_hq: null,
    file_output_guitar: null,
    file_output_guitar_hq: null,
    file_output_bass: null,
    file_output_bass_hq: null,
    file_output_drums: null,
    file_output_drums_hq: null,
    is_extracting_vocals: false,
    user: {
      id: "36384889-489c-44c6-9b25-289a95a1be9d",
      created_at: "2026-02-19T19:08:49.497Z",
      username: "yitek82056",
      display_name: "Test",
      image: null,
      image_thumbnail: null,
      total_followers: 0,
      client_plan_identifier: "FREE",
      client_plan_group: "FREE",
      bio: null,
      is_followed_by_requester: false,
      total_likes_received: 0,
      total_generations: 5,
    },
    bpm: null,
    generation_eta: 98,
    dominant_key: "",
    prompt_identifier: "27a0a301-e8b4-4ca9-9d33-769331122fe5",
    text_result: null,
    version_string: "Version 2",
    comment_count_total: 0,
    pending_comment_count: 0,
    is_liked_by_user: false,
    is_new: true,
    queue_number: 25413,
    is_vocals_ready: false,
    is_instrumental_ready: false,
    is_generated_via_tool: false,
    available_downloads: ["FULL_SONG"],
    featured_request_status: null,
    owner_feedback_tag: null,
    owner_feedback_message: null,
  },
];
