export const unprocessedGenerationMockData = [
  {
    id: "b5074c76-6043-433e-9276-09e2bf29e1d2",
    prompt: "test",
    created_at: "2026-02-21T20:12:42.215Z",
    status: "FAILED",
    error_tag: "BAD_REQUEST",
    queue_number: 26256,
    remained_credits: 400,
    error_message: "Feature Not Supported",
    error_message_detail:
      "Your request does not relate to audio or music features.",
    missing_input_fields: "[]",
    predicted_user_intent: "",
    parsed_error_tag: "",
    correction_type: "",
    error_image: "",
  },
  {
    id: "b5074c76-6043-433e-9276-09e2bf29e1d1",
    prompt: "test",
    created_at: "2026-02-21T20:12:42.215Z",
    status: "FAILED",
    error_tag: "SERVER_BUSY",
    queue_number: 26256,
    remained_credits: 400,
    error_message: "Oops Server Busy",
    error_message_detail: "4.9K users in the queue",
    missing_input_fields: "[]",
    predicted_user_intent: "",
    parsed_error_tag: "",
    correction_type: "",
    error_image: "",
  },
  {
    id: "d348997e-3bd4-4ade-a476-ad3d74602e5b",
    prompt: "Nepali",
    created_at: "2026-02-22T12:23:44.373Z",
    status: "FAILED",
    error_tag: "BAD_REQUEST",
    queue_number: 27351,
    remained_credits: 400,
    error_message: "Ambiguous Data",
    error_message_detail: "Please clarify your request.",
    missing_input_fields: "[]",
    predicted_user_intent: "Music AI",
    parsed_error_tag: "",
    correction_type: "",
    error_image: "",
  },
  {
    id: "4a17570f-fd13-4714-919c-26e733aff263",
    prompt: "This is the nepali song",
    created_at: "2026-02-22T12:23:31.371Z",
    status: "FAILED",
    error_tag: "BAD_REQUEST",
    queue_number: 27351,
    remained_credits: 400,
    error_message: "Ambiguous Data",
    error_message_detail: "Please clarify your request.",
    missing_input_fields: "[]",
    predicted_user_intent: "Music AI",
    parsed_error_tag: "",
    correction_type: "",
    error_image: "",
  },
];
